import { Metadata } from 'next';
import AIImageCheckerClient from './client';

export const metadata: Metadata = {
    title: 'AI Image Detector - Check Real or Fake Photos | Magetool',
    description: 'Detect whether an image was generated by AI or is a real photograph. Free online AI image checker using advanced analysis of artifacts and noise patterns.',
    keywords: ['ai image detector', 'fake image checker', 'ai photo checker', 'deepfake detector', 'real or ai', 'synthetic image detection', 'midjourney detector'],
    openGraph: {
        title: 'Free AI Image Detector - Real vs AI Checker | Magetool',
        description: 'Verify if an image is real or AI-generated with our advanced detection tool.',
        url: 'https://magetool.in/images/ai-checker',
    },
    alternates: {
        canonical: '/images/ai-checker',
    },
};

const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Magetool AI Checker',
    applicationCategory: 'UtilityApplication',
    operatingSystem: 'Web Browser',
    offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
    },
};

export default function AIImageCheckerPage() {
    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />
            <AIImageCheckerClient />
        </>
    );
}
